saitamau-maximum/id

workspaces/client/app/routes/login.tsx
workspaces/server/src/routes/auth.ts

refactor: cleanup debug thing (for avoiding auth)

---

workspaces/client/app/components/layout/dashboard.tsx
workspaces/client/app/components/layout/internal/sidebar.tsx
workspaces/client/app/hooks/use-repository.tsx
workspaces/client/app/repository/index.ts
workspaces/client/app/repository/member.ts
workspaces/client/app/routes.ts
workspaces/client/app/routes/home/page.tsx
workspaces/client/app/routes/members/internal/hooks/use-members.ts
workspaces/client/app/routes/members/page.tsx
workspaces/server/src/index.ts
workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/routes/member.ts
workspaces/server/src/usecase/repository/user.ts

feat: メンバーの一覧機能を作成

---

README.md

開発 doc を個人の OAuth App を使うように指示

---

workspaces/server/src/routes/user.ts

fix: register api's validation

---

pnpm-lock.yaml
workspaces/client/package.json
workspaces/server/package.json

resolve #24 
Valibot v1.0.0-beta.10のバグでした

fix: クライアントのidバリデーションを強化

---

pnpm-lock.yaml
workspaces/client/app/components/ui/button-like.tsx
workspaces/client/app/routes.ts
workspaces/client/app/routes/login/internal/components/login-button.tsx
workspaces/client/app/routes/login/page.tsx
workspaces/client/package.json

feat: ログインボタンのスタイルをGithub色で強調する

---

workspaces/client/app/components/layout/internal/sidebar.tsx
workspaces/client/app/constant.ts
workspaces/client/app/repository/user.ts
workspaces/client/app/root.tsx
workspaces/client/app/routes.ts
workspaces/client/app/routes/onboarding/internal/form.tsx
workspaces/client/app/routes/onboarding/page.tsx
workspaces/client/app/routes/settings/internal/components/form.tsx
workspaces/client/app/routes/settings/page.tsx
workspaces/client/app/schema/user.ts
workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/repository/user.ts
workspaces/server/src/routes/user.ts

feat: プロフィール情報を更新するページを作成

---

workspaces/client/app/components/ui/form/input.tsx
workspaces/client/app/components/ui/form/radio.tsx
workspaces/client/app/components/ui/form/select.tsx
workspaces/client/app/repository/member.ts
workspaces/client/app/routes/dashboard/members/internal/components/filter-form.tsx
workspaces/client/app/routes/dashboard/members/internal/hooks/use-members-filter.ts
workspaces/client/app/routes/dashboard/members/page.tsx

feat: メンバー検索機能の実装

---

pnpm-lock.yaml
workspaces/client/app/components/ui/menu/index.tsx
workspaces/client/app/routes/dashboard/internal/components/sidebar.tsx
workspaces/client/package.json

feat: introduce popup menu

---

.npmrc
pnpm-lock.yaml
workspaces/server/package.json
workspaces/server/src/db/seed/main.ts
workspaces/server/src/db/seed/senario/register-user.ts
workspaces/server/src/db/seed/senario/reset.ts

feat: seeder

---

workspaces/server/src/db/seed/main.ts
workspaces/server/src/db/seed/senario/register-user.ts
workspaces/server/src/db/seed/senario/reset.ts

fix: seeder

---

workspaces/client/app/components/feature/user/contribution/card.tsx
workspaces/client/app/components/feature/user/profile-card.tsx
workspaces/client/app/components/feature/user/role-badge.tsx
workspaces/client/app/repository/auth.ts
workspaces/client/app/repository/member.ts
workspaces/client/app/repository/oauth-apps.ts
workspaces/client/app/repository/user.ts
workspaces/client/app/routes/dashboard/admin/layout.tsx
workspaces/client/app/routes/dashboard/admin/users/internal/components/role-editor.tsx
workspaces/client/app/routes/dashboard/admin/users/internal/components/table.tsx
workspaces/client/app/routes/dashboard/admin/users/internal/hooks/use-update-role.ts
workspaces/client/app/routes/dashboard/home/page.tsx
workspaces/client/app/routes/dashboard/internal/components/sidebar.tsx
workspaces/client/app/routes/dashboard/members/internal/hooks/use-members-filter.ts
workspaces/client/app/routes/dashboard/members/page.tsx
workspaces/client/app/routes/dashboard/members/profile/page.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/page.tsx
workspaces/client/app/routes/dashboard/settings/internal/components/profile-image-cropper.tsx
workspaces/client/app/routes/dashboard/settings/internal/hooks/use-update-profile.ts
workspaces/client/app/routes/dashboard/settings/internal/hooks/use-upload-profile-image.ts
workspaces/client/app/routes/onboarding/internal/hooks/use-register.ts
workspaces/client/app/types/contribution.ts
workspaces/client/app/types/oauth.ts
workspaces/client/app/types/role.ts
workspaces/client/app/types/user.ts

refactor: とりあえずdomain typeを一箇所にまとめた

---

workspaces/server/src/db/seed/main.ts
workspaces/server/src/db/seed/senario/reset-register.ts
workspaces/server/src/infrastructure/repository/cloudflare/user.ts

feat(seed): add reset register for onboarding test

---

workspaces/client/app/components/feature/user/contribution/card.tsx
workspaces/client/app/components/feature/user/profile-card.tsx
workspaces/client/app/hooks/use-device-type.ts
workspaces/client/app/routes/dashboard/home/page.tsx
workspaces/client/app/routes/dashboard/layout.tsx
workspaces/client/app/routes/dashboard/members/profile/page.tsx
workspaces/client/panda.config.ts

fix: Dashboard Responsive

---

workspaces/client/app/constant.ts
workspaces/client/app/schema/user.ts
workspaces/server/src/constants/validation.ts
workspaces/server/src/routes/user.ts

feat: IDに予約語を使えないようにする

---

workspaces/client/app/components/ui/form/field/index.ts
workspaces/client/app/components/ui/form/field/text-area.tsx
workspaces/client/app/components/ui/icon-button.tsx
workspaces/client/app/repository/oauth-apps.ts
workspaces/client/app/routes/dashboard/oauth-apps/register/internal/hooks/use-register-oauth-app.ts
workspaces/client/app/routes/dashboard/oauth-apps/register/page.tsx
workspaces/client/app/schema/oauth.ts
workspaces/server/drizzle/0012_gigantic_proteus.sql
workspaces/server/drizzle/meta/0012_snapshot.json
workspaces/server/drizzle/meta/_journal.json
workspaces/server/src/constants/scope.ts
workspaces/server/src/db/schema/oauth/external.ts
workspaces/server/src/factory.ts
workspaces/server/src/index.ts
workspaces/server/src/infrastructure/repository/cloudflare/oauth-app-storage.ts
workspaces/server/src/infrastructure/repository/cloudflare/oauth-external.ts
workspaces/server/src/repository/oauth-external.ts
workspaces/server/src/repository/storage.ts
workspaces/server/src/routes/oauth/manage.ts
workspaces/server/src/shared/scope.ts

feat: [WIP] OAuth App System (登録)

---

pnpm-lock.yaml
workspaces/client/app/components/feature/user/user-display.tsx
workspaces/client/app/components/feature/user/user-selector.tsx
workspaces/client/app/components/logic/callable/comfirm.tsx
workspaces/client/app/components/logic/callable/information.tsx
workspaces/client/app/components/ui/form/select.tsx
workspaces/client/app/components/ui/toast/toast-stack.tsx
workspaces/client/app/repository/oauth-apps.ts
workspaces/client/app/root.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/app-edit-form.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/delete-secret-confirmation.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/generated-secret-display.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/manager-editor.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/secrets-manager.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/hooks/use-delete-secret.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/hooks/use-generate-secret.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/hooks/use-update-managers.ts
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/hooks/use-update-oauth-app.ts
workspaces/client/app/routes/dashboard/oauth-apps/config/page.tsx
workspaces/client/app/routes/dashboard/oauth-apps/home/page.tsx
workspaces/client/package.json
workspaces/server/src/infrastructure/repository/cloudflare/oauth-external.ts
workspaces/server/src/repository/oauth-external.ts
workspaces/server/src/routes/oauth/manage.ts

feat: oauth app editor

---

workspaces/client/app/repository/oauth-apps.ts
workspaces/server/src/routes/oauth/manage.ts

> うーんそもそもこのミドルウェアってidっていうパラメータあることが前提でしょ？
> :id -> :clientIdにしたいのと、verifyOAuthClientMiddlewareって名前が良さそう
_Originally posted by @sor4chi in https://github.com/saitamau-maximum/id/pull/104#discussion_r1976842878_
さすがに別 PR で

refactor: OAuth App の命名周り

---

workspaces/client/app/repository/oauth-apps.ts
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/app-edit-form.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/delete-confirmation.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/secrets-manager.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/hooks/use-delete-app.tsx
workspaces/server/src/db/schema/oauth/external.ts
workspaces/server/src/infrastructure/repository/cloudflare/oauth-external.ts
workspaces/server/src/repository/oauth-external.ts
workspaces/server/src/routes/oauth/manage.ts

feat: OAuth App の削除機能

---

workspaces/server/src/infrastructure/repository/cloudflare/oauth-external.ts
workspaces/server/src/repository/oauth-external.ts
workspaces/server/src/routes/oauth/index.ts
workspaces/server/src/routes/oauth/resources.ts
workspaces/server/src/routes/oauth/verifyToken.ts

パスは適当に `/oauth/resources/authuser` です

feat: OAuth Access Token で認証ユーザーを取得する API Route

---

workspaces/server/src/db/schema/oauth/external.ts
workspaces/server/src/infrastructure/repository/cloudflare/oauth-external.ts
workspaces/server/src/repository/oauth-external.ts
workspaces/server/src/routes/oauth/accessToken.ts
workspaces/server/src/routes/oauth/index.ts
workspaces/server/src/routes/oauth/manage.ts
workspaces/server/src/routes/oauth/resources.ts
workspaces/server/src/routes/oauth/verifyToken.ts

すみません...
#109 後に main merge します

fix: OAuth 周りの諸修正

---

workspaces/client/app/routes/login/page.tsx
workspaces/server/src/constants/env.ts
workspaces/server/src/middleware/auth.ts
workspaces/server/src/routes/auth-login/github.ts
workspaces/server/worker-configuration.d.ts
workspaces/server/wrangler.toml

ref: https://github.com/saitamau-maximum/id/pull/113#discussion_r1983071407 このへん
#113 後にマージする

refactor: CLIENT_ORIGIN を wrangler.toml に追加

---

workspaces/client/app/repository/user.ts
workspaces/client/app/routes/onboarding/internal/components/form.tsx
workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/routes/user.ts

bioは必須項目でないので登録障壁を下げるためにregisterから削除しました
現在のmainではonboarding(登録フロー)で正しくフォームを埋めてもフロント側のバリデーションに引っ掛かり登録できません
おそらくbioフォームの設置忘れかな？

fix: registerフローからbioを削除

---

workspaces/client/app/components/feature/user/certification-card.tsx
workspaces/client/app/routes/dashboard/home/page.tsx
workspaces/client/app/routes/dashboard/members/profile/page.tsx

- 資格アイテム文字色のトーンダウン
- Achievementセクション文字のサイズダウン
- パネルレイアウトに則ったモジュールのレイアウト
などなど軽微なデザインfixです
（レビューで伝えきれなかったのでPRです...ごめん）

fix: certification system UI fixup

---

workspaces/client/app/components/feature/calendar/calendar-cell.tsx
workspaces/client/app/components/feature/calendar/calendar.tsx
workspaces/client/app/components/feature/calendar/event-list.tsx
workspaces/client/app/components/feature/calendar/types.ts
workspaces/client/app/routes/dashboard/calendar/page.tsx
workspaces/client/panda.config.ts
workspaces/server/src/db/seed/senario/register-calendar.ts
workspaces/server/src/db/seed/senario/reset.ts

https://github.com/user-attachments/assets/4a64a373-d630-4354-aca6-005f438b678e

feat: Calendar Event UI

---

workspaces/client/app/components/feature/user/certification-card.tsx
workspaces/client/app/hooks/use-repository.tsx
workspaces/client/app/repository/auth.ts
workspaces/client/app/repository/certification.ts
workspaces/client/app/repository/index.ts
workspaces/client/app/repository/member.ts
workspaces/client/app/root.tsx
workspaces/client/app/routes/dashboard/home/page.tsx
workspaces/client/app/routes/dashboard/members/profile/page.tsx
workspaces/client/app/routes/dashboard/settings/internal/components/certification-request.tsx
workspaces/client/app/routes/dashboard/settings/internal/components/form.tsx
workspaces/client/app/routes/dashboard/settings/internal/hooks/use-send-certification-request.ts
workspaces/client/app/routes/dashboard/settings/page.tsx
workspaces/client/app/types/certification.ts
workspaces/client/app/types/user.ts
workspaces/server/drizzle/0015_illegal_network.sql
workspaces/server/drizzle/meta/0015_snapshot.json
workspaces/server/drizzle/meta/_journal.json
workspaces/server/src/db/schema/app.ts
workspaces/server/src/factory.ts
workspaces/server/src/index.ts
workspaces/server/src/infrastructure/repository/cloudflare/certification.ts
workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/repository/certification.ts
workspaces/server/src/repository/user.ts
workspaces/server/src/routes/certification.ts

feat: 資格・試験の申請部分

---

workspaces/client/app/repository/calendar.ts

related: https://github.com/saitamau-maximum/id/pull/137#discussion_r1994454176

fix: calendar key typing

---

workspaces/client/app/routes/dashboard/settings/internal/components/certification-request.tsx

fix: cert request の取得年 input を numeric に

---

workspaces/client/app/routes/dashboard/settings/internal/components/form.tsx

ネットワーク遅いと一生資格申請がdisabledになってる
それはもうこれでいい気がする

fix: 資格申請ボタンのUX改善

---

workspaces/client/app/components/ui/icon-button.tsx
workspaces/client/app/constant.ts
workspaces/client/app/repository/calendar.ts
workspaces/client/app/routes.ts
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-create-event-dialog.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-edit-event-dialog.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/events-editor.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/hooks/use-create-event.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/hooks/use-delete-event.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/hooks/use-update-event.tsx
workspaces/client/app/routes/dashboard/admin/events/page.tsx
workspaces/client/app/routes/dashboard/admin/layout.tsx
workspaces/client/app/routes/dashboard/calendar/hooks/use-calendar.ts
workspaces/client/app/routes/dashboard/settings/internal/components/form.tsx
workspaces/client/app/schema/event.ts
workspaces/client/app/schema/user.ts
workspaces/client/app/utils/valibot.ts
workspaces/server/src/infrastructure/repository/cloudflare/calendar.ts
workspaces/server/src/routes/calendar.ts

まだまだだけどとりあえずeditorだけ作りました
resolve #89

feat: event editor

---

workspaces/client/app/components/feature/user/profile-card.tsx
workspaces/client/app/components/feature/user/role-badge.tsx
workspaces/client/app/routes/dashboard/admin/users/internal/components/role-editor.tsx
workspaces/client/app/routes/dashboard/members/page.tsx
workspaces/server/src/constants/role.ts

誰もやらなそうなので一旦増やしておこう
なんか意見あったらここで議論しよう

feat: ロール増量キャンペーン

---

workspaces/client/app/routes/dashboard/admin/certifications/internal/components/certification-creator.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-create-event-dialog.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-create-location-dialog.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-edit-event-dialog.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-edit-location-dialog.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/internal/components/app-edit-form.tsx
workspaces/client/app/routes/dashboard/oauth-apps/register/page.tsx
workspaces/client/app/routes/dashboard/settings/internal/components/form.tsx
workspaces/client/app/routes/onboarding/internal/components/form.tsx

ミスってた型を色々なところで引き継いだ結果こうなってしまった

fix: incorrect form type

---

workspaces/server/src/routes/calendar/events.ts
workspaces/server/src/routes/calendar/location.ts

feat: strict role for calendar mutation

---

workspaces/client/app/components/ui/message-box.tsx
workspaces/client/app/constant.ts
workspaces/client/app/hooks/use-auth.ts
workspaces/client/app/repository/auth.ts
workspaces/client/app/repository/user.ts
workspaces/client/app/routes/dashboard/home/page.tsx
workspaces/client/app/types/user.ts
workspaces/server/drizzle/0021_crazy_silk_fever.sql
workspaces/server/drizzle/meta/0021_snapshot.json
workspaces/server/drizzle/meta/_journal.json
workspaces/server/src/db/schema/app.ts
workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/repository/user.ts

feat: 卒業生ステータスの追加、年度毎更新通知の実装

---

pnpm-lock.yaml
workspaces/client/app/repository/calendar.ts
workspaces/client/app/routes/dashboard/calendar/components/ical-display.tsx
workspaces/client/app/routes/dashboard/calendar/hooks/use-calendar.ts
workspaces/client/app/routes/dashboard/calendar/page.tsx
workspaces/server/package.json
workspaces/server/src/infrastructure/repository/cloudflare/calendar.ts
workspaces/server/src/repository/calendar.ts
workspaces/server/src/routes/calendar/events.ts
workspaces/server/src/routes/calendar/index.ts
workspaces/server/src/routes/calendar/location.ts

feat: ical api

---

workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-create-event-dialog.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/callable-edit-event-dialog.tsx
workspaces/server/src/routes/calendar/events.ts

fix(calendar): startAt >= endAt なeventを弾く

---

workspaces/flag/src/index.ts

chore: deflag invitation

---

workspaces/client/app/hooks/use-auth.ts
workspaces/client/app/repository/auth.ts
workspaces/client/app/repository/user.ts
workspaces/client/app/routes/dashboard/admin/users/internal/components/table.tsx
workspaces/client/app/routes/dashboard/admin/users/internal/hooks/use-confirm-payment.ts
workspaces/client/app/routes/dashboard/admin/users/page.tsx
workspaces/client/app/routes/dashboard/layout.tsx
workspaces/client/app/routes/login/page.tsx
workspaces/client/app/types/user.ts
workspaces/server/drizzle/0023_workable_mariko_yashida.sql
workspaces/server/drizzle/meta/0023_snapshot.json
workspaces/server/drizzle/meta/_journal.json
workspaces/server/src/db/schema/app.ts
workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/repository/user.ts
workspaces/server/src/routes/admin/user.ts
workspaces/server/src/routes/auth.ts

このPRじゃないけど追加でやらなきゃいけないこと
- Memberの一度退会後の復帰時、すでにuserがある状態でinviteできるようにする(支払い待機画面を見せるため)

feat: 既存ユーザーの年度移行のための支払い管理機能を追加

---

workspaces/client/app/constant.ts
workspaces/client/app/repository/user.ts
workspaces/client/app/routes/dashboard/settings/internal/components/form.tsx
workspaces/client/app/routes/onboarding/internal/components/form.tsx
workspaces/client/app/routes/onboarding/page.tsx
workspaces/server/src/routes/user.ts

feat: 学生情報をoptional化、フォームを学年ステータスによって出し分ける

---

workspaces/server/drizzle/0024_remove_alumni_role.sql

fix: 指定したカラムが違った

---

workspaces/server/src/infrastructure/repository/cloudflare/user.ts

fix: roleが空のときロールの追加を行わず関数を終了させる

---

workspaces/client/app/components/ui/dialog/index.tsx

resolve #227 
イベント作成・更新の dialog が変更を見やすいかも

fix: dialog の overflow

---

workspaces/client/app/components/feature/calendar/event-list.tsx
workspaces/client/app/routes/dashboard/admin/events/internal/components/events-editor.tsx
workspaces/client/app/utils/date.ts
workspaces/server/src/infrastructure/repository/discord/calendar.ts

↑ を修正しました (ref: https://github.com/saitamau-maximum/id/pull/237#pullrequestreview-2781460081)

fix: formatDuration の日付比較を修正 + 関連をリファクタリング

---

workspaces/server/drizzle/0027_furry_dormammu.sql
workspaces/server/drizzle/meta/0027_snapshot.json
workspaces/server/drizzle/meta/_journal.json
workspaces/server/src/db/schema/oauth/internal.ts
workspaces/server/src/index.ts
workspaces/server/src/infrastructure/repository/cloudflare/oauth-internal.ts
workspaces/server/src/infrastructure/repository/discord/bot.ts
workspaces/server/src/repository/discord-bot.ts
workspaces/server/src/repository/oauth-internal.ts
workspaces/server/src/repository/user.ts
workspaces/server/src/routes/auth-login/discord.ts
workspaces/server/src/routes/auth-login/github.ts

feat: OAuth Connection に Refresh Token を保持する

---

README.md
workspaces/server/src/routes/discord.ts

feat: impl add-discord-bot endpoint

---

workspaces/client/app/routes/dashboard/settings/internal/components/oauth-conn-row.tsx
workspaces/server/src/routes/auth-login/discord.ts
workspaces/server/src/routes/discord.ts

- avatar 未設定の時が微妙だった
- Server の nickname をつかう

fix: Discord の表示名と avatar 表示

---

workspaces/client/app/components/ui/toast/toast-item.tsx
workspaces/client/app/routes/dashboard/home/internal/components/discord-invitation-message-box.tsx
workspaces/client/app/routes/dashboard/home/internal/hooks/use-discord-invite.ts

feat: add "info" type for toast

---

workspaces/client/app/root.tsx
workspaces/client/app/routes/dashboard/admin/certifications/page.tsx
workspaces/client/app/routes/dashboard/admin/events/page.tsx
workspaces/client/app/routes/dashboard/admin/home/page.tsx
workspaces/client/app/routes/dashboard/admin/invites/page.tsx
workspaces/client/app/routes/dashboard/admin/layout.tsx
workspaces/client/app/routes/dashboard/admin/users/page.tsx
workspaces/client/app/routes/dashboard/calendar/page.tsx
workspaces/client/app/routes/dashboard/members/page.tsx
workspaces/client/app/routes/dashboard/members/profile/page.tsx
workspaces/client/app/routes/dashboard/oauth-apps/config/page.tsx
workspaces/client/app/routes/dashboard/oauth-apps/home/page.tsx
workspaces/client/app/routes/dashboard/oauth-apps/layout.tsx
workspaces/client/app/routes/dashboard/oauth-apps/register/page.tsx
workspaces/client/app/routes/dashboard/payment-info/page.tsx
workspaces/client/app/routes/dashboard/settings/page.tsx
workspaces/client/app/routes/invitation/page.tsx
workspaces/client/app/routes/login/page.tsx
workspaces/client/app/routes/onboarding/page.tsx
workspaces/client/app/routes/payment-info/page.tsx
workspaces/client/app/routes/verify.tsx
workspaces/server/src/db/schema/oauth/external.ts
workspaces/server/src/db/schema/oauth/internal.ts

resolve #229 
つけたタイトルは適当なので改善案あればぜひです

feat: ページタイトルを適切にする

---

workspaces/client/app/routes/login/page.tsx

feat: GitHub ログイン 404 Wiki

---

workspaces/server/src/infrastructure/repository/cloudflare/oauth-external.ts

fix: Access Token 削除を分割する

---

workspaces/client/app/components/ui/tab/tab-list.tsx

fix: Admin tab の overflow-x

---

workspaces/server/src/db/schema/app.ts
workspaces/server/src/db/schema/oauth/external.ts
workspaces/server/src/db/schema/oauth/internal.ts

https://github.com/drizzle-team/drizzle-orm/blob/33f0374e29014677c29f4b1f1dd1ab8fb68ac516/drizzle-orm/src/sqlite-core/table.ts#L90-L110 このへん
migration 更新はありません

refactor: Drizzle の書き方が変わったらしい

---

workspaces/server/src/infrastructure/repository/cloudflare/user.ts
workspaces/server/src/mocks/repository/user.ts
workspaces/server/src/repository/user.ts
workspaces/server/src/utils/oauth-login-provider.ts

feat: 一時退会後、Maximumに復帰するときユーザーデータがある状態で招待できるようにする

---

workspaces/server/src/infrastructure/repository/cloudflare/certification.ts
workspaces/server/src/mocks/repository/certification.ts
workspaces/server/src/repository/certification.ts
workspaces/server/src/routes/public.ts

これで public-website とかから取得できるようになります

feat: certification summary API 追加
